Description: 
   Services reuired for the Webapp to be hosted 

Parameters:

  WorkflowID:
      Description: An environment name that will be prefixed to resource names
      Type: String
  

Resources:

  EC21:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0557a15b87f6559cf  #Ubuntu22 
      SecurityGroupIds:  
        - Fn::ImportValue: InstanceSecurityGroup 
      SubnetId: !ImportValue "Public-Subnet1" 
      KeyName:  "nada"
      Tags: 
        - Key: Name
          Value: !Sub "ec2-${WorkflowID}"


  EC22:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0557a15b87f6559cf   #Ubuntu22 
      SecurityGroupIds:  
        - Fn::ImportValue: InstanceSecurityGroup 
      SubnetId:  !ImportValue "Public-Subnet2"
      KeyName: "nada"
      Tags: 
        - Key: Name
          Value: !Sub "ec2-${WorkflowID}"

  

       
